import Image from "next/image";
import React from "react";
import "./style.css";

type Props = {};

export default function LanguageSlice({}: Props) {
  return (
    <div className="relative flex flex-col gap-3 bg-[#3d3d3d] p-3 overflow-hidden">
      <div className="w-full flex gap-3">
        <Image
          className="slice-img"
          src="/images/languages/html.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/css.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/js.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/nodejs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/nextjs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/remixjs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/reactjs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/expressjs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/github.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/typescript.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/python.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/prisma.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/tailwind.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/bootstrap.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/sql.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/postgresql.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/mongodb.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/django.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/go.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/linux.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/ubuntu.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/vite.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/jest.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/docker.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/mui.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/figma.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/next-auth.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/html.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/css.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/js.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/nodejs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/nextjs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/remixjs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/reactjs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/expressjs.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/github.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/typescript.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/python.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/prisma.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/tailwind.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/bootstrap.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/sql.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/postgresql.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/mongodb.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/django.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/go.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/linux.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/ubuntu.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/vite.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/jest.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/docker.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/mui.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/figma.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
        <Image
          className="slice-img"
          src="/images/languages/next-auth.png"
          width={1000000}
          height={1000000}
          alt="logo"
        />
      </div>
      {/* <div className="w-full flex gap-3"></div> */}
    </div>
  );
}
